### ISSUE TITLE
phpstorm快捷鍵練習

### ISSUE THREAD

**Issue by ryan941** [mega-media/bootcamp#11]
# DESCRIPTION / 描述 *

熟悉phpstorm快捷鍵，正確使用IDE加快開發流程。

# FEATURE / 功能 *

[教學](http://goo.gl/ZBfgqT)
1. 開啟檔案( __⌘⇧O__ )
2. 開class檔( __⌘O__ )
3. 搜尋開啟檔案( __⌘F__ )
4. 搜尋整個專案( __⌘⇧F__ )
5. FTP設定與上傳( 
        設定：__⇧+Enter__
        上傳：__⌘⌥⇧Ｘ__
    )
6. 關閉檔案( __⌘W__ )
7. 新增檔案( __⌘N__ )
8. 刪除檔案( __Delete__ )
9. 偏好設定( __⌘,__ )
10. 開啟與關閉左側邊欄( __⌘1__ )
11. 命令列( __⌘⇧X__ )
12. 刪除一行( __⌘+Delete__ )
13. Generator( __⌘N or ⌥+Enter__ )

# HISTORY / 歷程紀錄 *

>0821
測試完成

# SCREENSHOTS / 截圖

# CKECKLIST / 審核清單 *

- [x] ~~新增 git branch~~
- [x] ~~pull request 審核 (# )~~
- [x] ~~視覺審核~~
- [x] ~~操作審核~~

**Comment by Ed0929** [comment]
@ryan941 Please check this, thx

**Comment by ryan941** [comment]
@Ed0929 不必要的 check list 可以 ~~刪掉沒關係~~

**Comment by Ed0929** [comment]
@ryan941 OK 之後我會先將不必要的check list刪掉
