### ISSUE TITLE
研讀 agent user API key

### ISSUE THREAD

**Issue by sin104** [mega-media/bootcamp#3]
# DESCRIPTION / 描述 *
研讀 現有的api key 如何產生
已及 外部 搓 api 時 key 的作用

# FEATURE / 功能 *
1.了解創立使用者，程式流程。
2.了解使用 api Key流程。  
3.規劃 實作部分。

# HISTORY / 歷程紀錄 *
08/03 @sin104
現行 api key 是寫死在 config->agent.php 裡面
api架構會 把代理帳號比對資料庫 使用到這key

現行user API key 為 亂數加密而成
sha1( uniqid ( mt_rand(), true ) )

08/10 @sin104
使用 api key 流程
先從 url input value 解析 拿到 config 代理資訊
再用 config 代理帳號 去撈資料庫 ...

08/11 @sin104
實作實驗方法Ａ，利用 microtime 計算時間差
就的方法有 code 這個欄位，在資料庫找不到相對應的值
必須再確認，此欄位作用。

方法Ａ:
       直接使用創造 user 時的 api_key  去做條件收尋 
做 function getClientUser() 掉認證這塊。 
經過時間，認證這塊 time_cost 為 0.0516 秒

# SCREENSHOTS / 截圖

# CKECKLIST / 審核清單 *

工程
~~- [ ] 新增 git branch~~
~~- [ ] pull request 審核 (# )~~
~~- [ ] 視覺審核~~
~~- [ ] 操作審核~~

**Comment by ryan941** [comment]
@sin104 這個issue 應該要開在 agent 才對。
